apiVersion: v1
kind: Pod
metadata:
  name: kubecommand
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - sleep
        - '5000'
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "100Mi"
          cpu: "200m"
      envFrom:
      - secretRef:
          name: bootjpasecret
