apiVersion: v1
kind: Pod
metadata:
  name: debian-command
  labels:
    app: debhost
spec:
  containers:
  - name: debiancommand1
    image: debian
    command: ["/bin/echo"]
    args: ["$(MESSAGE)"]
    env:
    - name: MESSAGE
      value: "hello World debiancommand1"
  - name: debiancommand2
    image: debian
    command: ["/bin/sh"]
    args: ["-c", "echo hello word debiancommand2; sleep 10; echo started container 2"]
    #args: ["-c", "while true; do echo hello; sleep 10;done"]
  restartPolicy: Never