apiVersion: v1
kind: Service
metadata:
  name: mybootjpa
  labels:
    run: mybootjpa
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: mybootjpa
