apiVersion: v1
kind: Pod
metadata:
  name: srvaccount-app
  labels:
    app: nginx-srvaccount
spec:
  volumes:
    - name: boot-jpa-secret
      secret:
        secretName: bootjpasecret
        defaultMode: 420
  containers:
    - name: nginx-contaienr
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
      resources:
        requests:
          memory: 50Mi
          cpu: 0.5m
        limits:
          memory: 100Mi
          cpu: 1m
      volumeMounts:
        - name: boot-jpa-secret
          readOnly: true
          mountPath: /etc/bootsecrets
      envFrom:
      - secretRef:
          name: db-secret
      env:
        - name: ENV_PROP_DEF_PROP
          valueFrom:
            configMapKeyRef:
              name: bootjpacgmp-2
              key: env.prop.def.prop
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: build-robot

