apiVersion: v1
kind: Pod
metadata:
  labels:
    app: multi-container
  name: multi-container
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
          protocol: TCP
      env:
        - name: DEPLOY_VERSION
          value: 1.14.2:3.11
        - name: DEPLOY_BY
          value: Ravi
    - name: alpine
      image: alpine:3.11
      ports:
        - containerPort: 81
          protocol: TCP
      env:
        - name: DEPLOY_VERSION
          value: 1.14.2:3.11
        - name: DEPLOY_BY
          value: Ravi