apiVersion: v1
kind: Pod
metadata:
  labels:
    app: multi-container
  name: multi-container
spec:
  replicas: 2
  containers:
    - name: nginx
      image: nginx:1.14.2
    - name: alpine
      image: alpine:3.11
  - env:
    - name: DEPLOY_VERSION
      value: 1.14.2:3.11
    - name: DEPLOY_BY
      value: Ravi
