apiVersion: v1
kind: Pod
metadata:
  labels:
    name: webapp-pod
  name: webapp-pod
spec:
  volumes:
    - name: db-secret-volume
      secret:
        secretName: db-secret
  containers:
    - image: nginx
      imagePullPolicy: Always
      name: webapp
      volumeMounts:
        - name: db-secret-volume
          mountPath: /etc/secrets
